//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DvsSapLink2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I:\\z_Temp\\Irene_Walt\\AutoCAD LT\\Archivierung AutoCAD\\testFiles\\autocad_work\\userw" +
            "ork")]
        public string PREPARE_SOURCE_DIRECTORY {
            get {
                return ((string)(this["PREPARE_SOURCE_DIRECTORY"]));
            }
            set {
                this["PREPARE_SOURCE_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I:\\z_Temp\\Irene_Walt\\AutoCAD LT\\Archivierung AutoCAD\\testFiles\\autocad_admin\\Arch" +
            "Pending")]
        public string PREPARE_DESTINATION_DIRECTORY {
            get {
                return ((string)(this["PREPARE_DESTINATION_DIRECTORY"]));
            }
            set {
                this["PREPARE_DESTINATION_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I:\\z_Temp\\Irene_Walt\\AutoCAD LT\\Archivierung AutoCAD\\testFiles\\autocad_admin\\logP" +
            "ending")]
        public string PREPARE_LOG_DIRECTORY {
            get {
                return ((string)(this["PREPARE_LOG_DIRECTORY"]));
            }
            set {
                this["PREPARE_LOG_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I:\\z_Temp\\Irene_Walt\\AutoCAD LT\\Archivierung AutoCAD\\testFiles\\autocad_admin\\Arch" +
            "Pending")]
        public string ARCHIVE_SOURCE_DIRECTORY {
            get {
                return ((string)(this["ARCHIVE_SOURCE_DIRECTORY"]));
            }
            set {
                this["ARCHIVE_SOURCE_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I:\\z_Temp\\Irene_Walt\\AutoCAD LT\\Archivierung AutoCAD\\testFiles\\archiv_autocad\\dwg" +
            "")]
        public string ARCHIVE_DESTINATION_DIRECTORY {
            get {
                return ((string)(this["ARCHIVE_DESTINATION_DIRECTORY"]));
            }
            set {
                this["ARCHIVE_DESTINATION_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I:\\z_Temp\\Irene_Walt\\AutoCAD LT\\Archivierung AutoCAD\\testFiles\\autocad_admin\\logA" +
            "rchiv\\DwgLog")]
        public string ARCHIVE_LOG_DIRECTORY {
            get {
                return ((string)(this["ARCHIVE_LOG_DIRECTORY"]));
            }
            set {
                this["ARCHIVE_LOG_DIRECTORY"] = value;
            }
        }
    }
}
