//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DvsSapLink2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V:\\AutoCAD_Data\\UserWork")]
        public string WORKING_DIRECTORY {
            get {
                return ((string)(this["WORKING_DIRECTORY"]));
            }
            set {
                this["WORKING_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V:\\AutoCAD_Admin\\ArchPending")]
        public string PENDING_DIRECTORY {
            get {
                return ((string)(this["PENDING_DIRECTORY"]));
            }
            set {
                this["PENDING_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V:\\Archiv_AutoCAD\\dwg\\bm")]
        public string ARCHIVE_DWG_DIRECTORY {
            get {
                return ((string)(this["ARCHIVE_DWG_DIRECTORY"]));
            }
            set {
                this["ARCHIVE_DWG_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V:\\AutoCAD_Admin\\logArchiv\\DwgLog")]
        public string ARCHIVE_LOG_DIRECTORY {
            get {
                return ((string)(this["ARCHIVE_LOG_DIRECTORY"]));
            }
            set {
                this["ARCHIVE_LOG_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V:\\AutoCAD_Admin\\SapPending\\dat_test")]
        public string SAPTRANSFER_DIRECTORY {
            get {
                return ((string)(this["SAPTRANSFER_DIRECTORY"]));
            }
            set {
                this["SAPTRANSFER_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V:\\AutoCAD_Admin\\logArchiv\\SapTransfer")]
        public string ARCHIVE_SAPTRANSFER_DIRECTORY {
            get {
                return ((string)(this["ARCHIVE_SAPTRANSFER_DIRECTORY"]));
            }
            set {
                this["ARCHIVE_SAPTRANSFER_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V:\\AutoCAD_Admin\\KonvPending")]
        public string CONVERSION_DIRECTORY {
            get {
                return ((string)(this["CONVERSION_DIRECTORY"]));
            }
            set {
                this["CONVERSION_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V:\\Archiv_AutoCAD\\txt")]
        public string ARCHIVE_TXT_DIRECTORY {
            get {
                return ((string)(this["ARCHIVE_TXT_DIRECTORY"]));
            }
            set {
                this["ARCHIVE_TXT_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V:\\Archiv_Tif")]
        public string ARCHIVE_TIF_DIRECTORY {
            get {
                return ((string)(this["ARCHIVE_TIF_DIRECTORY"]));
            }
            set {
                this["ARCHIVE_TIF_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roman.eckert")]
        public string DEFAULT_SAP_USER_ARCHIVE {
            get {
                return ((string)(this["DEFAULT_SAP_USER_ARCHIVE"]));
            }
            set {
                this["DEFAULT_SAP_USER_ARCHIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int DEFAULT_SAP_LABOR {
            get {
                return ((int)(this["DEFAULT_SAP_LABOR"]));
            }
            set {
                this["DEFAULT_SAP_LABOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RE")]
        public string DEFAULT_SAP_STATE_PREPARE {
            get {
                return ((string)(this["DEFAULT_SAP_STATE_PREPARE"]));
            }
            set {
                this["DEFAULT_SAP_STATE_PREPARE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RE")]
        public string DEFAULT_SAP_STATE_ARCHIVE {
            get {
                return ((string)(this["DEFAULT_SAP_STATE_ARCHIVE"]));
            }
            set {
                this["DEFAULT_SAP_STATE_ARCHIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DEFAULT_SAP_USER_PREPARE {
            get {
                return ((string)(this["DEFAULT_SAP_USER_PREPARE"]));
            }
            set {
                this["DEFAULT_SAP_USER_PREPARE"] = value;
            }
        }
    }
}
